name: Endpoint Unit Tests
agent:
    type: Unity::VM
    image: robotics/ci-ubuntu20:latest
    flavor: i1.medium
commands:
    - echo "Hello world!"
    - source /opt/ros/noetic/setup.bash && echo "ROS_DISTRO == $ROS_DISTRO" &&
        cd .. && mkdir -p catkin_ws/src && cp -r ./ROS-TCP-Endpoint catkin_ws/src &&
        cd catkin_ws && catkin_make && source devel/setup.bash && python3 -m pytest
triggers:
    expression: |
        pull_request.target eq "dev" AND
        NOT pull_request.push.changes.all match "**/*.md" AND
        NOT pull_request.source match "hotfix/.*"
